; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
description = DW3000 tests
default_envs = lolin32_lite



[env]
framework = arduino
monitor_speed = 115200 ;9600
build_type = debug ;release
build_flags =
    -D USING_ESP32
	-D MODE_DEBUG ;MODE_RELEASE
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_EXCEPTIONS
	-D DEVICE_ADDRESS=3

platform = espressif32@^6.3.2 ; espressif32

lib_deps = 
	; marzogh/SPIMemory@^3.4.0
	; densaugeo/base64@^1.2.0
	; fastled/FastLED @ ^3.10.3
debug_init_break = tbreak setup



[env:lolin32_lite]
debug_tool = esp-prog
board = lolin32_lite
build_flags =
	-DLOLIN32

